In [2]:
import numpy as np

In [2]:
np.ones((3,3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
np.array((3,2))
arr=np.random.random((1000,300))

In [40]:
ar=np.arange(24).reshape(2,3,4)
list_1 = [10,11,12,13] 
list_2 = [15,12,13,14]
x=np.array([list_1,list_2])

# x.size


In [43]:
ar=np.arange(19)

In [53]:
a=np.array([[1,2,3,4],[1,2,3,5],[8,7,3,2]])


In [66]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 5],
       [8, 7, 3, 2]])

In [1]:
a[:,1]

NameError: name 'a' is not defined

In [2]:
import numpy as np


In [15]:
arr=np.ones((3,5), dtype=np.int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
arr.shape

(3, 5)

In [17]:
arr=np.zeros((3,5), dtype=np.int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [1]:
arr.ndim

NameError: name 'arr' is not defined

In [2]:
import numpy as np



In [4]:
ar1= np.random.random((1000,1000))
ar2=np.array([1,4,5])
np.setdiff1d(ar1,ar2)

array([2, 3])